import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/provider/session-provider";
import { getServerSession } from "next-auth";
import AnimatePresence from "@/components/animation/animate-presence";
import options from "@/lib/auth/option";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { cn } from "@/lib/utils";
import MotionDivPage from "@/components/animation/motion-div-page";
import { Toaster } from "react-hot-toast";
import ModalProvider from "@/components/provider/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body
          className={cn(
            inter.className,
            "dark:bg-slate-900 bg-white",
            "flex flex-col"
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
          >
            <AnimatePresence>
              {/* <ThemeToggler /> */}
              <Toaster
                position="top-center"
                reverseOrder={false}
                gutter={8}
                containerClassName=""
                containerStyle={{}}
                toastOptions={{
                  className: "",
                  duration: 5000,
                  style: {
                    background: "#363636",
                    color: "#fff",
                  },
                }}
              />
              <main className="relative w-full h-full overflow-hidden">
                <ModalProvider />
                {children}
              </main>
            </AnimatePresence>
          </ThemeProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
